- name: Update yum cache
  yum:
    update_cache: yes

- name: Install nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm"

- name: Install nodejs
  shell: |
    source "{{ ansible_env.HOME }}/.nvm/nvm.sh" && nvm install 22

- name: Install npm
  yum:
    name: npm
    state: present

- name: Copy nodejs app from local repository
  ansible.builtin.synchronize:
    src: "{{ playbook_dir }}/../node_app/"
    dest: /home/ec2-user/app
    mode: push
    recursive: yes
    owner: yes
    group: yes

- name: Install npm dependencies
  npm:
    path: /home/ec2-user/app

- name: Install PM2
  npm:
    name: pm2
    global: yes

- name: Stop nodejs app (if running)
  command: pm2 stop /home/ec2-user/app/app.js
  ignore_errors: yes

- name: Start nodejs app
  command: pm2 start /home/ec2-user/app/app.js