name: Deploy Node.js App to EC2
on:
  push:
    paths:
      - 'node_app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from repository
        uses: actions/checkout@v3

      - name: Setup SSH Key for Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          SERVER_IP=$(ansible-inventory -i inventory --host nodejs_instance | jq -r '.ansible_host')

          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible playbook
        run: ansible-playbook ansible/deploy_app.yml